default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: head_note_development
test:
  <<: *default
  database: head_note_test
production:
  <<: *default
  database: head_note_production
  username: head_note
  password: <%= ENV['HEAD_NOTE_DATABASE_PASSWORD'] %>
